// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WareHouseAPI.Data;

#nullable disable

namespace WareHouseAPI.Migrations
{
    [DbContext(typeof(WareHouseAPIDbContext))]
    [Migration("20220930143435_DbContextsMigration")]
    partial class DbContextsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("WareHouseAPI.Models.tblInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("inventoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("wareHouseID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tblInventories");
                });

            modelBuilder.Entity("WareHouseAPI.Models.tblWarehouses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("wareHouseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tblWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
